# Generated by Django 4.0.3 on 2022-04-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, verbose_name='Name')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='Number')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Name')),
                ('phone', models.IntegerField(blank=True, verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': 'Сontact list',
            },
        ),
    ]
